spring:
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/esercizio85
        username: root
        password: claudio
    jpa:
        database: mysql
        show_sql: true
        hibernate:
            ddl-auto: update
    jackson:
        serialization:
            fail-on-empty-beans: false
    application:
        name: esercizio-85-spring-boot-custom-queries-1
